# Generated by Django 4.2.19 on 2025-02-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_user_remove_course_id_alter_course_code_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'UserActivities'},
        ),
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together=set(),
        ),
    ]
