# Generated by Django 4.2.19 on 2025-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_activity_options_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vm_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
